### ISSUE TITLE
Error: Cannot find module '@typescript-eslint/parser'

### ISSUE THREAD

**Issue by stevengrimaldo** [idahogurl/vs-code-prettier-eslint#11]
**Describe the bug**
Getting the error in vscode "Error: Cannot find module '@typescript-eslint/parser'"

**To Reproduce**
1. Go to vs code
2. Click on prettier bottom right
3. Select prettier Eslint
4. Click save on any file in code base

**Expected behavior**
No error

**Example Project**
Packages installed in the repo
prettier, prettier-eslint, @typescript-eslint/parser, eslint

**Screenshots**
![Screen Shot 2021-07-27 at 5 00 59 PM](https://user-images.githubusercontent.com/3181158/127233279-6bd42da5-419d-4b7e-a636-f1ddaa761fb8.png)

**Versions (please complete the following information):**
- Visual Studio Code: Version: 1.58.2
- Node: v12.19.0
- Package Manager npm 6.14.8
- prettier-eslint: latest
- prettier: latest
- eslint: latest

**System Specifications (please complete the following information):**
- OS: latest
 
**Additional context**
No google solutions found.

**Comment by idahogurl** [comment]
@stevengrimaldo Could you compare your setup with https://github.com/idahogurl/vs-code-prettier-eslint/tree/master/examples/typescript

**Comment by AndriyBroda** [comment]
> @stevengrimaldo Could you compare your setup with https://github.com/idahogurl/vs-code-prettier-eslint/tree/master/examples/typescript

Hi, first of all, thank you for the extension. But why can't we upgrade the version of ESLint and Prettier?

**Comment by stevengrimaldo** [comment]
All set, thanks!

**Comment by devamiya** [comment]
I am facing the same error. I have updated the dev dependencies as per the above example.
Is any update to this?

**Comment by devamiya** [comment]
Updated the .eslintrc working fine

**Comment by ownchoice** [comment]
I was having the same problem, turns out I was trying to use a plugin in my ESLint config file without the corresponding npm package installed.

I just removed the unused jsx-a11y plugin from my ESLint config.

I wasn't using JSX in my project but it had the following ESLint config:

```
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'plugin:jsx-a11y/recommended',
    'airbnb-base/legacy',
    'prettier',
  ],
  plugins: ['@typescript-eslint', 'prettier', 'jsx-a11y', 'import'],
```

Because I had copied the `.eslintrc.js` file from another project.

And I didn't have the `eslint-plugin-jsx-a11y` package installed, **installing it also fixes the issue**.
