### ISSUE TITLE
Failure when formatting Svelte file

### ISSUE THREAD

**Issue by zachstence** [idahogurl/vs-code-prettier-eslint#113]
**Describe the bug**
When trying to format a SvelteKit project, the files are not formatted because Prettier ESLint fails with an error.

**To Reproduce**
More detail in reproduction repo here https://github.com/zachstence/prettier-eslint-sveltekit

1. Create new SvelteKit project
2. Try to format with Prettier ESLint
3. Prettier ESLint fails because it can't find `prettier-plugin-svelte`

**Expected behavior**
Formatting should work without failure, like `prettier-eslint-cli` does.

**Example Project**
https://github.com/zachstence/prettier-eslint-sveltekit

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension: 5.0.4
- Visual Studio Code: 1.73.1
- Node: 16.17.1
- Package Manager: npm 8.15.0
- prettier: 2.7.1
- eslint: 8.27.0

**System Specifications (please complete the following information):**
- OS: Windows 10 Build 19044.2251
- Processor: Ryzen 5 5600X
- RAM Size: 32GB

**Comment by idahogurl** [comment]
@zachstence Thank you for all the reproduction material!! I will take a look.

**Comment by idahogurl** [comment]
@zachstence Here is the solution.

Rename your `.prettierrc` file to `.prettierrc.cjs`
Past the following as the contents

```
module.exports = {
	useTabs: true,
	singleQuote: true,
	trailingComma: 'none',
	printWidth: 100,
	plugins: [require('prettier-plugin-svelte')],
	overrides: [{ files: '*.svelte', options: { parser: 'svelte' } }]
};
```

**Comment by idahogurl** [comment]
@zachstence Can I close this?

**Comment by zachstence** [comment]
Sorry for taking a while to get back to you. Just tried your solution on my end, and it works! Thanks for your help.
