### ISSUE TITLE
Why using this extension instead Prettier + ESLint

### ISSUE THREAD

**Issue by ncoquelet** [idahogurl/vs-code-prettier-eslint#13]
Hi,
I'm pretty sure there are many good reasons for the existence of this extension but it's not describe in the readme !
I use official Prettier + Eslint Extensions without issue. Why I should abandon them in favor of this extension ?

Thanks a lot

**Comment by idahogurl** [comment]
@ncoquelet This extension does not replace the need for the ESLint extension. You still have to use the ESLint extension if you want it to highlight issues. 

My extension only "replaces" the Prettier extension. If you have ESLint formatting rules enabled in your ESLint configuration, then you have to run both `eslint --fix` + `prettier`. Previously the official Prettier extension did not have an option to run ESLint formatting additionally. It's a setting you have to enable and mine works out of the box.
