### ISSUE TITLE
Saving Code is taking forever

### ISSUE THREAD

**Issue by Ayushi-Sharma** [idahogurl/vs-code-prettier-eslint#14]
Issue Type: <b>Performance Issue</b>

I closed VSCode multiple times yet it was not saving the way it should. It has hanged multiple times. 
Unable to work with this hanging again and again

Extension version: 3.0.4
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 6|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 0fbb31b0-bbe3-4cbe-9006-c8a724aa29a4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    6	    90	 14148	code main
    5	    33	 14151	   gpu-process
    0	    16	 14153	   utility
   11	   180	 14154	   window (SingleSelect.spec.jsx — railsApp)
    0	    41	 14482	     extensionHost
    0	    16	 14490	       electron_node tsserver.js 
    0	    90	 14491	       electron_node tsserver.js 
    0	    25	 14504	         electron_node typingsInstaller.js typesMap.js 
    0	    25	 14922	       /private/var/folders/tq/_54xtqw965x9vhz2cgy4j46r0000gp/T/AppTranslocation/232EE0EB-37DB-4D84-B600-0162F8980FB0/d/Visual Studio Code 2.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/tq/_54xtqw965x9vhz2cgy4j46r0000gp/T/AppTranslocation/232EE0EB-37DB-4D84-B600-0162F8980FB0/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=14482
    0	    16	 14483	     watcherService
    0	    16	 14487	     searchService
   97	    57	 14484	   shared-process
    0	     0	 16558	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	    66	 16556	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SingleSelect.spec.jsx — railsApp)
|    Folder (railsApp): 18544 files
|      File types: html(2838) rb(2325) png(2145) js(2128) erb(1372) jsx(1316)
|                  scss(896) svg(801) jpg(400) map(190)
|      Conf files: package.json(3) launch.json(1) settings.json(1) makefile(1)
|                  gulp.js(1) jsconfig.json(1) webpack.config.js(1)
|      Launch Configs: chrome node;
```

</details>

**Comment by kristiannotari** [comment]
Ok I tried multiple times and with .eslintignore and .prettierignore files it does save instantly and everything seems to work fine. I've looked within this extension source code and I think it's hardcoded the retrieving of ignore files by finding .eslintignore and .prettierignore files. Would be cool to have an option to change cli execution parameters for both eslint and prettier, like what I'm doing with my package.json scripts (eg. `eslint . --ext .ts --ignore-path .gitignore`)

**Comment by idahogurl** [comment]
@kristiannotari Sorry I didn't see you replied!! You'd have to see if the `prettier-eslint` package allows you pass in other CLI options. I'm thinking it doesn't

**Comment by kristiannotari** [comment]
Yeah, after a brief look, it seems to not support it. There are other "competitors" that seem to support the ignore path/file option though, the ones specified at the end of the `prettier-eslint` readme. I've also checked both eslint and prettier are currently developing a better ignore configurable system, based on configuration too (instead of just the cli) but there are no great advancements in this regard.
