### ISSUE TITLE
How to do the prettier last as in the cli ?

### ISSUE THREAD

**Issue by MatthD** [idahogurl/vs-code-prettier-eslint#140]
How is it possible with the vscode extension to do the same as https://github.com/prettier/prettier-eslint#prettierlast-boolean  with the cli?

Id does not product the same result with this option

**Comment by idahogurl** [comment]
@MatthD The option is not available as I have not had anyone request the feature as of yet. Feel free to create a PR if you can. I've been thinking about adding `Format on Paste` and `Format on Type` support.
