### ISSUE TITLE
`parserOptions#project` for TS parser breaks ESLint stage

### ISSUE THREAD

**Issue by Hetch3t** [idahogurl/vs-code-prettier-eslint#141]
**Describe the bug**

`parserOptions#project` breaks extension functionality for TS projects. For all the steps below output for Prettier ESLint is completely silent.

**To Reproduce**
- Have `parserOptions: { project: './tsconfig.json' }` in `eslintrc.json` in TypeScript project
- Restart VSCode
  - Try to format any `.ts` file via extension - same result as I would've run just Prettier (I tested). Though ESLint extension does show errors.
  - Try to format any `.js` file via extension - result as expected
  - Try to format same file `prettier-eslint-cli` via command, e.g. `yarn run prettier-eslint src/some_file.ts --write` - result as expected
- Remove `parserOptions: { project: './tsconfig.json' }` from `eslintrc.json` (and rules required to it)
- Restart VSCode
  - Try to format any `.ts` file via extension - result as expected (except for removed rules of course)

**Example**
- This is working example repo: https://github.com/Hetch3t/eslint-config-serenity
- This is not: https://github.com/Hetch3t/eslint-config-serenity/tree/failing-project-ts
- This is PR: https://github.com/Hetch3t/eslint-config-serenity/pull/4/files

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension: 5.0.4
- Visual Studio Code: 1.73.1
- Node: 18.13.0
- Package Manager: yarn 1.22.19
- prettier: 2.8.3
- eslint: 8.32.0
- prettier-eslint: 15.0.1
- @typescript-eslint/eslint-plugin: 5.48.2
- @typescript-eslint/parser: 5.48.2

**System Specifications (please complete the following information):**
- OS: MacOS Ventura 13.1
- Processor: 2,6 GHz 6-Core Intel Core i7
- RAM Size: 16 GB

**Comment by idahogurl** [comment]
@Hetch3t Try the `js` extension again and make sure your `project` matches the values found in this example `.eslintrc.js` file
https://github.com/idahogurl/vs-code-prettier-eslint/blob/c387cdaaa1a82f47c83edfb09c03ae10372bb7f8/examples/typescript/.eslintrc.js#L5-L8

**Comment by Hetch3t** [comment]
@idahogurl :
Setting the `tsconfigRootDir` fixed it! Closing.
