### ISSUE TITLE
It doesn't decrease the line size for me

### ISSUE THREAD

**Issue by imthedaniel** [idahogurl/vs-code-prettier-eslint#144]
**Describe the bug**
![image](https://user-images.githubusercontent.com/67215758/217346782-0be10fba-ff0a-420f-b311-1e8c61b9ab45.png)

I configured the .editorconfig file to have a maximum of 99 characters per line, but the extension keeps undoing my formatting and increasing the line.

My package json: https://pastebin.com/raw/09e0mZc5
eslintrc.json: https://pastebin.com/raw/kafXj7h0

.editorconfig:
root = true

[*]
indent_size = 2
indent_style = space
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
ax_line_length = 99

I don't know why it happens that the extension doesn't help me, not decreasing the line size.

**Comment by imthedaniel** [comment]
> @imthedaniel Is your project using TypeScript?

yes

**Comment by imthedaniel** [comment]
> @imthedaniel Is your project using TypeScript?

yes

**Comment by idahogurl** [comment]
@imthedaniel Try the fix described here:
https://github.com/idahogurl/vs-code-prettier-eslint/issues/27#issuecomment-1026444484

**Comment by idahogurl** [comment]
@imthedaniel Did the fix resolve your issue?

**Comment by imthedaniel** [comment]
@idahogurl Thanks a lot for all your support, I had to install 2 additional libraries to get it to work:

eslint-config-prettier and eslint-plugin-prettier

Greetings from Brazil!

**Comment by idahogurl** [comment]
@imthedaniel Interesting. You shouldn't need to install those. That means Prettier isn't running, just ESLint and you wouldn't need my extension.

**Comment by imthedaniel** [comment]
But if I disable its extension, the code formatting doesn't happen anymore

**Comment by ashley-jisc** [comment]
I'm also experiencing this issue.

No errors in the output for prettier-eslint, vscode will highlight in red about the max-len Eslint rule violation but formatting the document with this formatter doesn't act upon that rule violation.

I do have the fix applied as described as above
