### ISSUE TITLE
How do I set the eslintrc‘s path?

### ISSUE THREAD

**Issue by xiaocaibird** [idahogurl/vs-code-prettier-eslint#146]
We want to have only a few rules for formatting.
Because the “--fix” of some rules can cause bugs.

**Comment by idahogurl** [comment]
@xiaocaibird You cannot set the path. The extension starts at the directory of the file being formatted and looks up until it finds the `eslintrc`

**Comment by jungwookim** [comment]
Hi @idahogurl , I know that the config file is found by being traversed up but do you think that we may support other configurations to support https://github.com/prettier/prettier-eslint#options ?

**Comment by idahogurl** [comment]
@jungwookim I could support some of the options in https://github.com/prettier/prettier-eslint#options. I don't have time however to implement any enhancements currently. Feel free to create a PR similar to what I did to implement `pretterLast`
https://github.com/idahogurl/vs-code-prettier-eslint/pull/150

**Comment by jungwookim** [comment]
@idahogurl Thanks. I'm going to make a PR later. No problem!
