### ISSUE TITLE
Cannot find module 'vue-eslint-parser'

### ISSUE THREAD

**Issue by zp00v0518** [idahogurl/vs-code-prettier-eslint#147]
Hello!
I have reinstalled plugin and it stopped to work.

![Screenshot 2023-02-22 145140](https://user-images.githubusercontent.com/35657518/220630179-ff1f32a4-4a1a-427c-9b6a-f5de5dcc5821.jpg)
![Screenshot 2023-02-22 151506](https://user-images.githubusercontent.com/35657518/220630644-69bc2c98-c37b-4c9e-87a0-53d3348d70a3.jpg)

OS: Windows 11

**Comment by idahogurl** [comment]
@zp00v0518 Are you using Typescript?

**Comment by zp00v0518** [comment]
> @zp00v0518 Are you using Typescript?

Hш. I am not using Typescript. 
But, I have to say, Prettier-Eslint started to work. Although I didn't do anything to fix the bugs.
It's kind of magic, honestly)
