### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nehalbadelhafez** [idahogurl/vs-code-prettier-eslint#15]
- Issue Type: `Performance`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `3.0.4`
- OS Version: `Linux x64 5.11.0-36-generic`
- VS Code version: `1.60.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/rvest.vs-code-prettier-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by idahogurl** [comment]
@nehalbadelhafez Thank you for creating an issue and providing some help to resolve it. I am aware of performance issues with quad-core or smaller processors. Being on Windows NT makes me think you are on an older machine. I need the `cpuprofile.txt` to know what is causing this issue.

Do you have autosave set to `onFocusChange`?

**Comment by nehalbadelhafez** [comment]
Hi,
I'm not on windows I'm on ubuntu 20.04, I do have autosave set to
onFocusChange and please tell me where I can find the cpuprofile.txt file.
Regards,
Nehal

**Comment by idahogurl** [comment]
@nehalbadelhafez My bad. I was copying a response for a similar issue. What is your processor?

**Comment by nehalbadelhafez** [comment]
My processor model is Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz

**Comment by idahogurl** [comment]
@nehalbadelhafez That would be the issue. According to https://cpu.userbenchmark.com/Intel-Core-i5-3317U/Rating/2744 your processor is a duo core. My extension has issues with with quad-core or smaller processors. Unfortunately there is nothing I can do because I am dependent on the ESLint & Prettier CLI.

**Comment by nehalbadelhafez** [comment]
Ok, thanks for the clarification.
