### ISSUE TITLE
Format exceeds length

### ISSUE THREAD

**Issue by unmatchedbest** [idahogurl/vs-code-prettier-eslint#153]
hello，For the code with too long chain, the format will exceed the length. If you break the line, the format will be changed back into one line. I hope to improve it。
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/34122670/223006483-ce2012b8-9ecf-4a34-8fb8-e29eeedbbfd1.png">
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/34122670/223006590-08a52633-c32d-4f7b-a424-712f5e2b8849.png">

**Comment by idahogurl** [comment]
@unmatchedbest Could I get a repository or a ZIP of the simple project reproducing the issue? You'll need to include all the configuration files (package.json, .eslintrc, .prettierrc, etc)

**Comment by unmatchedbest** [comment]
I created a simple project. Please see, this is the git address.

https://github.com/unmatchedbest/mypro.git

**Comment by idahogurl** [comment]
@unmatchedbest I'm not seeing your ESLint configuration file

**Comment by unmatchedbest** [comment]
Sorry, it was hidden when uploading, and then it was omitted. It has already been added.

**Comment by idahogurl** [comment]
@unmatchedbest I get a 404 when trying to install the package `@tencent/eslint-config-tencent`. I did find the package `eslint-config-tencent` and that worked.

**Comment by unmatchedbest** [comment]
Sorry, I'll just remove this package and solve the problem. Thank you.
