### ISSUE TITLE
Getting "Error: r is not a constructor" in Windows VSCode > Output > Prettier Eslint

### ISSUE THREAD

**Issue by wadewadewadewadewadewade** [idahogurl/vs-code-prettier-eslint#16]
**Describe the bug**
I'm trying to get the [Prettier Eslint](https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint) plugin to run in Windows VScode, but I only see "Error: r is not a constructor" in VSCode > Output > Prettier Eslint

**To Reproduce**
1. Open a .tsx file with intentionally ugly formatting and see no errors
2. Open the Prettier Eslint extension output window by opening View > Output and selecting "Prettier Eslint" from the dropdown in the right
3. Hit ctrl+alt+F (or force Formatting with Prettier Eslint) to force the file to be parsed
4. See "Error: r is not a constructor"

**Expected behavior**
I'd expect to see error messages for the incorrect, ugly formatting.

**Example Project**

https://github.com/wadewadewadewadewadewade/ineffectua.com

(Here's the ugly file I'm using for testing: https://github.com/wadewadewadewadewadewade/ineffectua.com/blob/main/src/common/components/posts/post/Post.tsx)

**Screenshots**

![image](https://user-images.githubusercontent.com/23270394/136856768-48d1f91a-e459-4583-958c-fa834fa96ae3.png)

**Versions (please complete the following information):**
- Visual Studio Code: 1.6.1.0
- Node: 14.18.0
- Package Manager: npm 6.14.15
- prettier-eslint: 13.0.0
- prettier: 2.4.1
- eslint: 8.0.0

**System Specifications (please complete the following information):**
- OS: Windows 11
- Processor: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
- RAM Size: 32.0 GB
 
**Additional context**
I seem to have the same problem with this project in WSL 2, if that's useful information.

**Comment by MarkSky** [comment]
I have the same error.
I also found some information in Developer Tools:
![Prettier-eslint](https://user-images.githubusercontent.com/4032734/137073439-d5fed244-7c1c-4307-9a30-9edf5acfb65b.jpg)

**Comment by idahogurl** [comment]
@UnstoppableMango @MarkSky I believe this is an error with Prettier ESLint. It may not support Node 16 or there is a bug in the latest version. Could you downgrade to the supported versions listed in the README. I should put that Node 14 is supported. I want to upgrade the ESLint & Prettier. I'm probably going to create a beta VSX for people to download.

**Comment by idahogurl** [comment]
@wadewadewadewadewadewade 

It was a configuration issue. You do not need to specify the ES version in the `env` section if you are using TypeScript. I got it to work by making changes to these files.

**.eslintrc.json**

```json
{
    "env": {
        "browser": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
    },
    "settings": {
        "react": {
            "version": "detect"
        }
    }
}
```

**package.json**

```json
"devDependencies": {
    "@types/draftjs-to-html": "^0.8.1",
    "@types/jsonwebtoken": "^8.5.5",
    "@types/multiparty": "0.0.33",
    "@types/react": "^17.0.27",
    "@types/react-draft-wysiwyg": "^1.13.3",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.0",
    "eslint-plugin-react": "^7.26.1",
    "husky": "^7.0.2",
    "prettier": "^2.4.1",
    "prettier-eslint": "^13.0.0",
    "pretty-quick": "^3.1.1",
    "typescript": "^4.4.3"
  }
```

**Comment by wadewadewadewadewadewade** [comment]
@idahogurl Awesome, that basically got me 99% of the way there - thank you!

one additional thing I had to do was change `"ecmaVersion": "latest"` to `"ecmaVersion": 12` because of this similar error I then got (once eslint was parsing everything correctly): https://github.com/eslint/eslint-scope/issues/55

Also, I installed eslint 7.28.0 because some of the dependencies of the typescript parser asked for that.

Thank you for solving my prettier-problems, and for writing the extension in the first place!

**Comment by MurzNN** [comment]
I've got the same issue, but downgrading isn't help, it is reproducible on clean project with those files:
`package.json`:
```json
{
  "name": "vscode-lint",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "6.8.0",
    "prettier": "1.9.1",
    "prettier-eslint": "10.1.0"
  }
}
```
`.eslintrc.js`
```js
module.exports = {
    "env": {
        "browser": true,
        "es2017": true
    },
    "extends": [
        "eslint:recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 13,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
    }
};
```
`index.ts`
```ts
let a = 1;
let b = 2
a = b + 23
```
And when I'm trying to launch `Format Document With` » `Prettier ESLint` - I see the error in output:
```
Error: r is not a constructor
```

Can you recommend any fixes for this?

**Comment by MurzNN** [comment]
Upgrading to beta version https://github.com/idahogurl/vs-code-prettier-eslint#beta-download resolves the issue for me!

**Comment by jodik** [comment]
> I had to downgrade to `eslint@7` and then this error went away.

Downgraded to eslint@7.32 resolved the issue for me too. It's weird tho as prettier-eslint requires officially eslint@^8.7.0
