### ISSUE TITLE
ESLint stage not being applied when `parserOptions.project` is set

### ISSUE THREAD

**Issue by zikaari** [idahogurl/vs-code-prettier-eslint#160]
Exact same issue as https://github.com/idahogurl/vs-code-prettier-eslint/issues/38, except in my case I can't use the fix that OP did which is to avoid using `parserOptions.project`.

Nothing surfaces to the `Output` panel.

`prettier-eslint --write **/*.ts` works as expected without any problems.

The updated context information is updated below:

**Versions:**
- VS Code Prettier ESLint extension: 5.1.0
- Visual Studio Code: 1.77.1
- Node: 17.3.1
- Package Manager: yarn@1.22.15
- prettier: 2.8.7.
- eslint: 8.38.0

**System Specifications:**
- OS: Windows 10 using WSL2
- Processor: i7
- RAM Size: 16
 
**Additional context**

**Comment by idahogurl** [comment]
@zikaari The solution is not #38 but to follow the example project instead. You'll need to name your ESLint config file as `.eslintrc.js` file. Then copy the project value found here https://github.com/idahogurl/vs-code-prettier-eslint/blob/master/examples/typescript/.eslintrc.js

**Comment by danielwerg** [comment]
@idahogurl For me adding just `parserOptions: { tsconfigRootDir: __dirname },` was enough. Would it be possible to skip that part? I would prefer to have more minimalistic config.
