### ISSUE TITLE
Sometimes the plugin works very slowly

### ISSUE THREAD

**Issue by oxilor** [idahogurl/vs-code-prettier-eslint#165]
At first, thank you for this plugin! Special thanks for the fact that it allows to work with multiple projects at once (the prettier/eslint configs are located in nested directories, not in the parent [root/apps/app1, root/apps/app2, etc]).

Some time ago, the plugin started working very slowly (see [video](https://youtu.be/0IasZOBz8MU)). It takes from 10 seconds to several minutes to format the code in a file. At this point, if I run prettier manually using the command line (`prettier --write <file_path>`), then it's executed instantly.

I don't know how to determine which command is being executed when the plugin freezes. The output is always empty (cmd+shift+U -> Output -> Prettier Eslint).

**Versions:**
- VS Code Prettier ESLint extension: 5.1.0
- Visual Studio Code: 1.78.2
- Node: 20.0.0
- Package Manager: yarn 1.22.19
- prettier: 2.8.8
- eslint: 8.40.0

**System Specifications:**
- OS: MacOS Ventura 13.3.1 (a)
- Processor: 2,6 GHz 6-Core Intel Core i7
- RAM Size: 16 GB 2400 MHz DDR4

**Comment by idahogurl** [comment]
@oxilor Thank you for writing up the issue and providing the video. Your computer specs more than adequate so that shouldn't be the issue. Can you provide an example repo with a minimal reproduction?

**Comment by oxilor** [comment]
@idahogurl I'll try to create a repo that reproduces this issue at the end of this week. However, it'll be quite difficult to do, because I don't know what exactly causes this problem. When I run VSCode, first ~5 minutes everything is fine, then a file saving takes about 10 seconds, then about a minute or more.

Is it possible to log a command that is executed by this extension? I want to understand whether this command is executed at all in this case, and if it is, which one command with which arguments is executed. Then I can run the same command manually and check it.

**Comment by idahogurl** [comment]
@oxilor It's not running command is the thing. It calls the `format` function from the `prettier-eslint` package which in turn calls the format functions of the uses the eslint and prettier packages.
