### ISSUE TITLE
Settings Improvement

### ISSUE THREAD

**Issue by DirectorRen-TV** [idahogurl/vs-code-prettier-eslint#178]
It would be nice to have an ability to split .prettierignore и .eslintignore files. 
For formatting styles in Vue SFC files I use prettier, and for other files I use eslint. Accordingly, I fill the .prettierignore file with *.ts and *.js values, and then eslint-part of plugin does not fix *.ts and *.js files - because of "File ignored. Matches entry in .eslintignore or .prettierignore".

Thanks for the plugin, this was really a salvation for formatting only styles block in SFC

**Comment by GreenTea124** [comment]
Some additional suggestions from my side:

# Feature idea

I think this plugin could support 4 new VS Code settings like this:

```jsonc
// .vscode/settings.json
{
	// Existing
	"vs-code-prettier-eslint.prettierLast": false,
	// New
	"vs-code-prettier-eslint.eslintConfigPath": ".eslintrc.fix.json",
	"vs-code-prettier-eslint.eslintIgnorePath": ".gitignore",
	"vs-code-prettier-eslint.prettierConfigPath": "prettier.config.js",
	"vs-code-prettier-eslint.prettierIgnorePath": ".gitignore",
}
```

# Why?

Some ESLint rules can be quite slow, and running them on every Ctrl+S can become laggy if you frequently save your files to format them. With my ESLint setup, sometimes I have to wait 10+ seconds, and sometimes VSCode refuses to format things entirely, it just keeps loading until I reset it.

To address this, I propose additional settings, that would allow two-config setups. One ESLint config could be used by `ESLint Plugin` for full linting and in-editor error messages (`.eslintrc.js`), and another one could be very tiny and used by `Prettier ESLint Plugin` for auto-formatting (`.eslintrc.fix.json`).

+ custom ignore files as already suggested.
