### ISSUE TITLE
How to i disable copy and paste variable auto add  semi-colon  end of text;

### ISSUE THREAD

**Issue by SonPham1602** [idahogurl/vs-code-prettier-eslint#181]
When i using extension it auto format code when copy and paste variable
![image](https://github.com/idahogurl/vs-code-prettier-eslint/assets/43876888/fca10ac5-3708-4cb8-8738-f53d98b59e92)

**Comment by zhangzhuang15** [comment]
<img width="967" alt="截屏2023-08-22 18 19 49" src="https://github.com/idahogurl/vs-code-prettier-eslint/assets/74013184/681ed627-324d-4aa5-bfa4-be7f531bd4c2">


Open settings panel in your vscode, then search format, finally uncheck `Format on Paste`.

**Comment by zhangzhuang15** [comment]
你好 ，您发给我的邮件我已经收到。
