### ISSUE TITLE
Not compatible with prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by dvakatsiienko** [idahogurl/vs-code-prettier-eslint#183]
**Describe the bug**
Extension errors out with `Error: Cannot find module 'prettier-plugin-tailwindcss'` when `prettier-plugin-tailwindcss` is added as a plugin to `.prettierrc.js`.

**To Reproduce**
1. `npm i prettier-plugin-tailwindcss`
2. Add `prettier-plugin-tailwindcss` as a plugin to `.prettierrc.js`
3. Restart VSCode
4. Open «Output» section of VSCode and select `Prettier ESLint`
5. Format a document
6. Observer error `Error: Cannot find module 'prettier-plugin-tailwindcss'`

**Expected behavior**
Extension should support simple tailwind plugin for class sorting.

**Example Prettier Config**

```js
/** @type {import("prettier").Config} */
module.exports = {
    tailwindFunctions: ['clsx'],
    plugins: ['prettier-plugin-tailwindcss'],
};
```

**Screenshots**
![Screenshot 2023-08-25 at 16 58 52@2x](https://github.com/idahogurl/vs-code-prettier-eslint/assets/15727958/dcfd6458-11e9-4d8a-b15d-06545ac242b7)
<img width="826" alt="Screenshot 2023-08-25 at 16 59 14@2x" src="https://github.com/idahogurl/vs-code-prettier-eslint/assets/15727958/a017f9ab-845e-406e-90f1-832ba9529343">

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension v5.1.0
- VSCode v1.81.1 (Universal)
- Node: 18.12.0
- Package Manager pnpm 8.6.12
- prettier: 2.8.8
- eslint: 8.47.0

**System Specifications (please complete the following information):**
- OS:macOS Ventura 13.4.1 (c) (22F770820d)
- Processor: M1 Max
- RAM Size: 64GB

**Comment by idahogurl** [comment]
@dvakatsiienko If you look closely at your error message, you'll see the error is coming from the `esbenp.prettier` extension not mine.

**Comment by dvakatsiienko** [comment]
Yes, you're right. I've accidentally had two prettiers installed.
After deleting an official one, the same error persists, pointing to this extension.

```
Error: Cannot find module 'prettier-plugin-tailwindcss'
Require stack:
- /Users/furthur/Projects/_anadea/rocky-ui-gitlab/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js
- /Users/furthur/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
-  
Error: Cannot find module 'prettier-plugin-tailwindcss'
Require stack:
- /Users/furthur/Projects/_anadea/rocky-ui-gitlab/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js
- /Users/furthur/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
    at Function.s._resolveFilename (node:electron/js2c/utility_init:2:2740)
    at g.resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:709)
    at /Users/furthur/Projects/_anadea/rocky-ui-gitlab/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38119:25
    at Array.map (<anonymous>)
    at Object.load (/Users/furthur/Projects/_anadea/rocky-ui-gitlab/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38114:65)
    at Object.load [as loadPlugins] (/Users/furthur/Projects/_anadea/rocky-ui-gitlab/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:16147:23)
    at /Users/furthur/Projects/_anadea/rocky-ui-gitlab/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38181:24
    at Object.format (/Users/furthur/Projects/_anadea/rocky-ui-gitlab/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38197:12)
    at /Users/furthur/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:189:131
    at zme (/Users/furthur/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:185:1460)
```

<img width="1000" alt="Screenshot 2023-08-29 at 17 17 58@2x" src="https://github.com/idahogurl/vs-code-prettier-eslint/assets/15727958/fcc77029-e175-4bb7-947d-f7987da53278">

**Comment by idahogurl** [comment]
@dvakatsiienko I wonder if the issue is that you are using PNPM as your package manager. Can you use the `pretter` CLI and see if you get the same error?

**Comment by dvakatsiienko** [comment]
@idahogurl I've tried to wipe out `pnpm` and use `yarn` with same configuration, it produces same error.

**Comment by jedimonkey** [comment]
I've had some success with this wrapping the plugins with `require.resolve`
See https://github.com/prettier/prettier/issues/13276

**Comment by bravo-kernel** [comment]
Works great with https://github.com/francoismassart/eslint-plugin-tailwindcss
