### ISSUE TITLE
Not Implementing Eslint Typescript Rules in Pretiiter

### ISSUE THREAD

**Issue by syntistx** [idahogurl/vs-code-prettier-eslint#19]
**Describe the bug**
For example, when i run prettier-eslint on normal project it follows the rules
Like trailing comma and single qutoes
But in TypeScript it doesn't enforce those rules and i ended up with errors in my code

```
import { useTranslation } from 'react-i18next';

import './i18n';
import './App.scss';

export const App = () => {
  const { t } = useTranslation();
  return (
    <div className="App">
      {t('welcome')}
    </div>
  );
};
```

After Format Document with Prettier-eslint

```
import { useTranslation } from "react-i18next";

import "./i18n";
import "./App.scss";

export const App = () => {
  const { t } = useTranslation();
  return <div className="App">{t("welcome")}</div>;
};
```

eslint config: 

```
{
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": [
    "plugin:react/recommended",
    "airbnb",
    "airbnb-typescript",
    "airbnb/hooks",
    "plugin:react/jsx-runtime"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2021,
    "sourceType": "module"
  },
  "plugins": [
    "react",
    "@typescript-eslint"
  ],
  "rules": {
    "import/prefer-default-export": "off",
    "import/no-default-export": "off",
    "react/jsx-props-no-spreading": "off",
    "react/no-unescaped-entities": 0
  }
}
```

**Comment by idahogurl** [comment]
@syntistx I'll take a look when I can. For now can you see if using the `prettier-eslint` CLI gives you the same result. Also, check the `examples` folder inside this repository. A lot of errors are caused by an issue in the ESLint config file. The example TypeScript project does work with my extension as expected.

**Comment by rowanfreeman** [comment]
I have the same problem when using [eslint-config-standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript)

```json
{
  "extends": ["standard-with-typescript"],
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "rules": { "comma-dangle": ["error", "always-multiline"] },
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"],
      "parserOptions": {
        "project": "tsconfig.json"
      }
    }
  ]
}
```

![eslint errors](https://i.imgur.com/3ZHfp9T.png)

I can tell eslint to autofix the problems, which it does, but then when I save the file, it gets changed back.

**Comment by idahogurl** [comment]
@syntistx I created a test repository and was able to reproduce the behavior. However, unlike @rowanfreeman using the `prettier-eslint-cli`, I got the same result. This appears to be an issue with the `prettier-eslint` package. Could you create an issue on their repository?

**Comment by idahogurl** [comment]
@rowanfreeman I also created a test repository with your configuration. I finally figured it out after some debugging the `prettier-eslint` package. The issue was that using the `format` function doesn't resolve the path of the `tsconfig.json` file. Setting the full path of `tsconfig.json` works!!

```js
const path = require('path')
module.exports = {
  extends: ['standard-with-typescript'],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  rules: { 'comma-dangle': ['error', 'always-multiline'] },
  overrides: [
    {
      files: ['*.ts', '*.tsx'], // Your TypeScript files extension
      parserOptions: {
        project: [path.join(__dirname, 'tsconfig.json')], // Specify it only for TypeScript files
      },
    },
  ],
}
```

**Comment by hakula139** [comment]
It seems like setting `tsconfigRootDir` to `__dirname` instead of `'.'` also works for me. Great thanks!

```javascript
parserOptions: {
  // ...
  project: './tsconfig.eslint.json',
  tsconfigRootDir: __dirname,  // instead of '.'
},
```
