### ISSUE TITLE
Error: Cannot find module 'eslint' which is already installed

### ISSUE THREAD

**Issue by nikkehtine** [idahogurl/vs-code-prettier-eslint#197]
**Describe the bug**
Going into the `Output > Prettier ESLint` tab, I get `Error: Cannot find module 'eslint'` every time I save the file.
Prettier, ESLint and prettier-eslint are all installed globally on my machine, and the problem persists even when I install them as a dev dependency in my project.

**Versions:**
- VS Code Prettier ESLint extension 5.1.0
- VSCodium: 1.84.2
- Node: 20.9.0
- pnpm: 8.10.5
- prettier: 3.1.0
- eslint: 8.54.0

**System Specifications:**
- OS: Windows 10 22H2
- Processor: Intel Core i5 4-core 3.5GHz
- RAM Size: 16 GB
 
I couldn't find any information on what could cause this issue and how to fix it. If it's out there then I'm terribly sorry.

**Comment by mattbrannon** [comment]
Prettier 3.0 switched entirely to ESModules. Try downgrading prettier to version 2.8.8
```
pnpm remove prettier && pnpm add prettier@2.8.8
```

**Comment by wysok** [comment]
The same here.

**Versions:**

VS Code Prettier ESLint extension 5.1.0
VSCodium: 1.85.0 (Universal)
Node: 18.18.2
npm: 9.8.1
prettier: 2.8.8
eslint: 8.15.0

**System:**
macOS 13.6.1 (22G313)
Chip Apple M2

```Error: Cannot find module 'eslint'
Require stack:
- /Users/[MY_USER]/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
```

**Comment by zhangzhuang15** [comment]
Look at [this](https://github.com/idahogurl/vs-code-prettier-eslint/issues/180#issuecomment-1845171357), it might help you @wysok
