### ISSUE TITLE
Is there a way that the two folders can be formatted separately？

### ISSUE THREAD

**Issue by syymo** [idahogurl/vs-code-prettier-eslint#2]
![image](https://user-images.githubusercontent.com/26571594/122556180-c4ff2400-d06d-11eb-94e2-8ef1012b81e2.png)

hello，My project client is web，server is API server，
two project but in one.
two project all install @typescript-eslint/parser、prettier、prettier-eslint
client is can format，but server Error: Cannot find module '@typescript-eslint/parser'.

Is there a way that the two folders can be formatted separately？

**Comment by idahogurl** [comment]
@syymo I need some reproduction steps and/or access to a sample repository.

**Comment by idahogurl** [comment]
Closing due to over 30 days of inactivity.
