### ISSUE TITLE
A question, not a bug: can I 

### ISSUE THREAD

**Issue by tobewisebeforeiamold** [idahogurl/vs-code-prettier-eslint#20]
**Describe the bug**
This is actually a question more than a bug: can I see that the eslint rules are running after the prettier rules?

For example, my `.prettierrc.json` file looks like this:
```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "printWidth": 80,
  "useTabs": true,
  "semi": true,
  "singleQuote": true,
  "bracketSpacing": true,
  "bracketSameLine": false
}
```

And my .eslintrc.js file has these rules:
```
'array-bracket-spacing': [ 'error', 'always' ],
'space-before-function-paren': [ 'error', {
	'named': 'never',
	'anonymous': 'never',
	'asyncArrow': 'always',
} ],
'arrow-spacing': [ 'error', { 'before': true, 'after': true } ],
'space-before-blocks': [ 'error', 'always' ],
'computed-property-spacing': [ 'error', 'always' ],
```

...applying prettier-eslint formating turns that into this (removing the spacing in the parens):
```
const someFunction = (param1, param2) => {
```

If I run `prettier --write . && eslint .` from the command line the spacing in the parens remains consistent (removed by prettier and added back in by eslint)

**To Reproduce**
1. If I have code that looks like this...
  ```
  const someFunction = ( param1, param2 ) => {
  ```
2. ...applying prettier-eslint formatting in VSCode turns that into this (removing some spacing in the parens):
  ```
  const someFunction = (param1, param2) => {
  ```

**Expected behavior**
If I run `prettier --write . && eslint --fix .` from the command line the spacing in the parens remains consistent (removed by prettier and added back in by eslint)

**Example Project**

Hopefully the provided info above is enough and you can let me know of a value or setting somewhere off of the top of your head based on that description that would let prettier run and then eslint run. But if not I can take a moment and build out a sample repo.

**Screenshots**
N/A

**Versions (please complete the following information):**
- Visual Studio Code: 1.62.2
- Node: 12.16.1
- Package Manager: 6.13.4
- prettier-eslint: ^13.0.0
- prettier: ^2.4.1
- eslint: 7.32.0

**System Specifications (please complete the following information):**
- OS: Windows 11 (upgraded from Windows 10 Pro)
- Processor: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
- RAM Size: 32GB
 
**Additional context**
Many thanks!

**Comment by idahogurl** [comment]
@tobewisebeforeiamold This extension is using the 'prettier-eslint' package. Could you try the [CLI](https://github.com/prettier/prettier-eslint-cli) of prettier-eslint and see if you get the same result? Also, are you using the beta version of the plugin made for Prettier 2?

**Comment by tobewisebeforeiamold** [comment]
Sure thing!

I installed prettier-eslint-cli ^5.0.1 and that seems to work as desired with eslint running after prettier...at least with respect to the example above and the spacing within the parens.

In case it's useful, my eslint config is in a js file/module and my prettier config is in a json file. Is it possible that the VSCode extension doesn't like my eslint config being a .js file/module?

**Comment by idahogurl** [comment]
@tobewisebeforeiamold Hmmmm...that is strange. Using JS for your ESLint config file shouldn't be a factor. All my code does is get the text from the file you are saving and then return the output from calling the `format` function from `prettier-eslint` I'll try to reproduce it as soon as I can.

**Comment by tobewisebeforeiamold** [comment]
Awesome, thank you!

Some additional info in case it's useful:

I have the Prettier `esbenp.prettier-vscode` extension installed as well.

When I look at my settings filtering for "Prettier" I see 28 settings that seem to be associated with that "Prettier" extension and not the "Prettier-ESLint" extension?

![image](https://user-images.githubusercontent.com/93224599/142462934-2151b9bc-da26-4c3a-98ed-9a773bb55013.png)

Thanks again for taking a look!

**Comment by idahogurl** [comment]
@tobewisebeforeiamold I was able to reproduce the behavior. However, after trying `yarn run prettier-eslint *.js` with the Prettier ESLint CLI, I get `const someFunction = (param1, param2) => {};` It's a `prettier-eslint` issue. Could you report this error to that repository?

**Comment by tobewisebeforeiamold** [comment]
Weird, that's interesting that you get the incorrect behavior from the CLI!

**Comment by tobewisebeforeiamold** [comment]
Should I still open an issue with the CLI?

**Comment by idahogurl** [comment]
@tobewisebeforeiamold If you can't reproduce it on the CLI then don't report it. Perhaps the best thing is for you to push the project up to a repository.

**Comment by idahogurl** [comment]
I cloned your sample repository. I was able to get the correct behavior with the CLI. I also was able to get the correct behavior with my extension but that's because I'm using the 4.0 beta version which supports Prettier 2 & ESLint 7. On the main README you'll find a section about the Beta Version here https://github.com/idahogurl/vs-code-prettier-eslint#beta-download

**Comment by tobewisebeforeiamold** [comment]
Rad, I'm totally down to try out that beta version. Thank you!
