### ISSUE TITLE
Proposal: move to prettier organization to collaborate

### ISSUE THREAD

**Issue by JounQin** [idahogurl/vs-code-prettier-eslint#200]
As title.

cc @fisker

**Comment by idahogurl** [comment]
I know it would allow for better collaboration. However, I have worked on this plugin basically solo and I'd like to see if I can't get some sponsorship for my work.

**Comment by JounQin** [comment]
I think you can just keep the sponsor sections in this repo, that's totally fine to me.

**Comment by fisker** [comment]
Welcome to join us.

**Comment by JounQin** [comment]
@idahogurl Hi, if you're also interested, you can discus at https://github.com/prettier/prettier-eslint/issues/949.
