### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Leslie-L55** [idahogurl/vs-code-prettier-eslint#21]
- Issue Type: `Performance`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `3.0.4`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.62.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\admin\AppData\Local\Temp\rvest.vs-code-prettier-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by idahogurl** [comment]
@Leslie-L55 Thank you for creating an issue and providing some help to resolve it. I am aware of performance issues with quad-core or smaller processors. Being on Windows NT makes me think you are on an older machine. I need the `cpuprofile.txt` to know what is causing this issue.

Do you have autosave set to `onFocusChange`?

**Comment by Leslie-L55** [comment]
我的c:\Users\admin\AppData\Local\Temp下没有该文件

**Comment by idahogurl** [comment]
@Leslie-L55 Thank you for creating an issue and providing some help to resolve it. I am aware of performance issues with quad-core or smaller processors. Being on Windows NT makes me think you are on an older machine. I need the cpuprofile.txt to know what is causing this issue.

Do you have autosave set to onFocusChange?
