### ISSUE TITLE
Extension cannot resolve globally installed prettier-eslint

### ISSUE THREAD

**Issue by aminomancer** [idahogurl/vs-code-prettier-eslint#216]
**Describe the bug**
With the 6.0 update, the extension is no longer working in any repositories where prettier-eslint is not installed locally, even though I have it installed globally. I also tried reinstalling it and switching node/npm versions, to no avail. This is troubling for me since I work on very large repositories with already established workflows, so I can't just add prettier-eslint to every package I work on. So I've had to use an old version of the extension, even though the newer version works on my other repos.

I'm thinking this is unexpected behavior because the readme says:

> This extension requires the following NPM packages to be installed either locally or **_globally_**:
> - `prettier-eslint@^16.1.2`

**To Reproduce**
Not sure about STR, just starting vscode I immediately see the following:
```
Error: Could not warm up worker. Formatting a file for the first time may take longer than usual.
Message: Cannot find module 'prettier-eslint'
Require stack:
- c:\Users\shmed\.vscode\extensions\rvest.vs-code-prettier-eslint-6.0.0\dist\extension.js
- c:\Users\shmed\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\shmed\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\shmed\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
```

The module is definitely installed and working for all other purposes:
```
$ npm list -g
C:\Program Files\nodejs -> .\
├── @typescript-eslint/parser@5.0.1-alpha.22+6746b8cc
├── corepack@0.12.1
├── eslint@8.52.0
├── npm@8.15.0
├── prettier-eslint@16.1.2
├── prettier@3.1.0
├── typescript@4.4.4
└── yarn@1.22.19
```

I'm using [nvm-windows](https://github.com/coreybutler/nvm-windows) but I also tried a standard npm installation.

**Expected behavior**
Extension should be able to find global modules

**Example Project**
This is happening with all projects, until I install prettier-eslint locally in them. I first noticed it on [mozilla-central](https://hg.mozilla.org/mozilla-central/) but I'm getting the same issue everywhere, e.g. here's a [simple example](https://github.com/aminomancer/GoatBots-Card-Watcher).

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension: 6.0.0
- Visual Studio Code: 1.86.2 (user setup)
- Node: 21.6.2, plus node for all my installed npm versions
- Package Manager: npm 19.0.0, 18.10.0, 17.2.0, 16.17.1, 15.8.0, 14.15.4, 12.3.1
- prettier: 2.8.8 and 3.1.0
- eslint: 8.56.0 and 8.52.0

**System Specifications (please complete the following information):**
- OS: Windows 10 (build 19045)
- Processor: Ryzen 9 5950X
- RAM Size: 64 GB
 
**Additional context**
I assume module resolution problems have more to do with my environment than anything else, so let me know if there are any logs I can provide that would help with debugging.

I haven't looked at the extension's source code, but this is the same error you'll see when you try to import a global module without first linking it, so I wonder if the extension is just naively importing `prettier-eslint` and assuming it will resolve as normal. But I don't know how you could practically link a global module to a vscode extension.

This might be the same issue as #197. It seems that one was closed automatically without resolution.

**Comment by TargiX** [comment]
Same issue here, Macos, Sonoma

**Comment by wanderBee** [comment]
Same issue here

**Comment by Kuro091** [comment]
Same issue, was going crazy over this!

**Comment by laholstege** [comment]
same issue on mac sonoma

**Comment by CoLdAs1cE** [comment]
same :(

**Comment by Marckon** [comment]
https://stackoverflow.com/questions/55771578/cant-find-the-module-after-extension-is-installed
```
cd ~/.vscode/extensions
cd your.extension
npm install
```
should work. 
(I am not sure if this is a bug of this extension or vscode itself, as I didn't encounter this before updating vscode to its latest version.)

**Comment by aminomancer** [comment]
> [stackoverflow.com/questions/55771578/cant-find-the-module-after-extension-is-installed](https://stackoverflow.com/questions/55771578/cant-find-the-module-after-extension-is-installed)
> 
> ```
> cd ~/.vscode/extensions
> cd your.extension
> npm install
> ```
> 
> should work.

I suppose it's better than rolling back, but I would still prefer if the extension can just find the global modules so we don't have to reinstall node modules every time the extension updates.

> (I am not sure if this is a bug of this extension or vscode itself, as I didn't encounter this before updating vscode to its latest version.)

I feel like extensions should at least be able to locate global modules if the `NODE_PATH` environment variable is set, the way a script running in node can normally do regardless of where it's running. So there may very well be a vscode bug, although I have encountered this issue on both the latest prod version of vscode and the previous one.

**Comment by acron0** [comment]
> https://stackoverflow.com/questions/55771578/cant-find-the-module-after-extension-is-installed
> 
> ```
> cd ~/.vscode/extensions
> cd your.extension
> npm install
> ```
> 
> should work. (I am not sure if this is a bug of this extension or vscode itself, as I didn't encounter this before updating vscode to its latest version.)

This worked for me, although a little trickier to find as I am using Codespaces. For me the dir was 
`/home/codespace/.vscode-remote/extensions/rvest.vs-code-prettier-eslint-6.0.0`

**Comment by aminomancer** [comment]
@idahogurl Is there any chance this can be fixed? Thanks.

**Comment by narin** [comment]
Still a bug

**Comment by kcchandra-w6** [comment]
> https://stackoverflow.com/questions/55771578/cant-find-the-module-after-extension-is-installed
> 
> ```
> cd ~/.vscode/extensions
> cd your.extension
> npm install
> ```
> 
> should work. (I am not sure if this is a bug of this extension or vscode itself, as I didn't encounter this before updating vscode to its latest version.)

this one does the job for me, thanks, no more error in output vscode. but why we need to do this? Idk, hope this going to be fixed soon

**Comment by gabrielcastelan** [comment]
Still a bug

**Comment by VirtualDOMinic** [comment]
> https://stackoverflow.com/questions/55771578/cant-find-the-module-after-extension-is-installed
> 
> ```
> cd ~/.vscode/extensions
> cd your.extension
> npm install
> ```
> 
> should work. (I am not sure if this is a bug of this extension or vscode itself, as I didn't encounter this before updating vscode to its latest version.)

Thank you so much! Can confirm this still fixes it. In my case with `rvest.vs-code-prettier-eslint`. Thanks for saving me a bunch of time!
