### ISSUE TITLE
update 6.0 cannot be used

### ISSUE THREAD

**Issue by 909288037** [idahogurl/vs-code-prettier-eslint#218]
**Describe the bug**
Installed dependencies according to the documentation and updated the plugin to version 6.0, but encountering an error in the Windows environment: Error: Cannot find package 'prettier-plugin-organize-imports' imported from D:\Microsoft VS Code\noop.js. How can this issue be resolved?

![image](https://github.com/idahogurl/vs-code-prettier-eslint/assets/29726587/4e232c90-eed3-4c40-9298-5fc9c9cbab52)

**To Reproduce**
yarn add -D prettier@^3.1.0 eslint@^8.52.0 prettier-eslint@^16.1.2 @typescript-eslint/parser@^5.0.1 typescript@^4.4.4

**Expected behavior**
success

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension 6.0
- Visual Studio Code: [v1.87.2]
- Node: [v16.14.2]
- Package Manager [ npm 8.5.0, yarn 1.22.18, pnpm 8.10.3]
- prettier: [3.2.5]
- eslint: [8.52.0]

**System Specifications (please complete the following information):**
- OS: [Windows 10]
- Processor: [Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz   2.90 GHz]
- RAM Size: [16 GB]

**Comment by yellow444** [comment]
`Error: Cannot find package 'prettier-plugin-organize-imports' imported from C:\Program Files\Microsoft VS Code Insiders\noop.js
    at __node_internal_ (file:///d:/repos/qlab/ms-frontend/node_modules/prettier/index.mjs:16460:11)`
