### ISSUE TITLE
not compatible with eslint 9+?

### ISSUE THREAD

**Issue by nullbio** [idahogurl/vs-code-prettier-eslint#222]
I think this is because the plugin does not appear to be compatible with eslint 9?

```
Error: Could not warm up worker. Formatting a file for the first time may take longer than usual.
Message: Invalid Options:
- Unknown options: ignorePath, resolvePluginsRelativeTo, rulePaths, useEslintrc
- 'resolvePluginsRelativeTo' has been removed.
- 'ignorePath' has been removed.
- 'rulePaths' has been removed. Please define your rules using plugins.
Stacktrace: Error: Invalid Options:
- Unknown options: ignorePath, resolvePluginsRelativeTo, rulePaths, useEslintrc
- 'resolvePluginsRelativeTo' has been removed.
- 'ignorePath' has been removed.
- 'rulePaths' has been removed. Please define your rules using plugins.
    at processOptions (/node_modules/eslint/lib/eslint/eslint-helpers.js:839:15)
    at new ESLint (/node_modules/eslint/lib/eslint/eslint.js:593:34)
    at getESLint (/node_modules/prettier-eslint/dist/utils.js:337:12)
    at getESLintConfig (/node_modules/prettier-eslint/dist/index.js:268:39)
    at analyze (/node_modules/prettier-eslint/dist/index.js:80:77)
    at format (/node_modules/prettier-eslint/dist/index.js:50:13)
    at file:///home/node/.vscode-server/extensions/rvest.vs-code-prettier-eslint-6.0.0/dist/worker.mjs:1:1516
```

Here's a github issue having the same errors due to version incompatibility, hence why I assume this is the reason:

https://github.com/vercel/next.js/issues/64409

**Comment by dpnova** [comment]
Confirmed here too

**Comment by mattbrannon** [comment]
ESLint version 9 deprecated `.eslintrc` files in favor of what they call "flat configs" which essentially are just javascript objects with a similar but slightly different structure. https://eslint.org/docs/latest/use/configure/configuration-files

If you're trying to use the new config format, it won't work until the extension is updated.

You should be able to do one of the following to get things working:
- Set `ESLINT_USE_FLAT_CONFIG=false` in a `.env` file
- Downgrade ESLint to version 8

**Comment by linyuqing222** [comment]
Wow! I hope it can be supported.

**Comment by dpnova** [comment]
FWIW I use this setting now: `"editor.defaultFormatter": "esbenp.prettier-vscode",` no need for the extra vscode extension. Just configure eslint correctly with the prettier rules and use `prettier-vscode` as your formatter.

**Comment by Sayrix** [comment]
> FWIW I use this setting now: `"editor.defaultFormatter": "esbenp.prettier-vscode",` no need for the extra vscode extension. Just configure eslint correctly with the prettier rules and use `prettier-vscode` as your formatter.

But by doing that you're not using eslint anymore, only prettier

**Comment by dpnova** [comment]
> > FWIW I use this setting now: `"editor.defaultFormatter": "esbenp.prettier-vscode",` no need for the extra vscode extension. Just configure eslint correctly with the prettier rules and use `prettier-vscode` as your formatter.
> 
> But by doing that you're not using eslint anymore, only prettier

I use eslint to tell me things are wrong, but not formatting. That's right. There's a couple of rules I have to get vscode to fix for me.
