### ISSUE TITLE
`Error: Cannot find package 'prettier-plugin-organize-imports' imported from C:\Program Files\Microsoft VS Code Insiders\noop.js

### ISSUE THREAD

**Issue by yellow444** [idahogurl/vs-code-prettier-eslint#230]
`Error: Cannot find package 'prettier-plugin-organize-imports' imported from C:\Program Files\Microsoft VS Code Insiders\noop.js
    at __node_internal_ (file:///d:/repos/qlab/ms-frontend/node_modules/prettier/index.mjs:16460:11)`

_Originally posted by @yellow444 in https://github.com/idahogurl/vs-code-prettier-eslint/issues/218#issuecomment-2271724782_

**Comment by kriscoleman** [comment]
<img width="1662" alt="image" src="https://github.com/user-attachments/assets/6750dc58-3025-440c-a528-d8246ea08cea">

I tried the following steps on mac: 
1. `cd ~/.vscode/extensions`
2. `ls` to list the extensions 
3. `cd <name of rvest.prettier extension directory>` 
4. `npm i` 
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/b18b14ce-497d-40c2-98fa-4f6e954b3c74">
then output for extension showed: 
<img width="1708" alt="image" src="https://github.com/user-attachments/assets/4ebd4a03-ffdd-4ce9-a800-12d01d048f26">

**Comment by yellow444** [comment]
> <img alt="image" width="1662" src="https://private-user-images.githubusercontent.com/21978023/380791165-6750dc58-3025-440c-a528-d8246ea08cea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTExMDQsIm5iZiI6MTczMjcxMDgwNCwicGF0aCI6Ii8yMTk3ODAyMy8zODA3OTExNjUtNjc1MGRjNTgtMzAyNS00NDBjLWE1MjgtZDgyNDZlYTA4Y2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZWVhOWZjMzIwNDEzYWU1OGQzMGEzZmEyYzVhMjM5NWY0NmY0OTQwNGY1ZGIyYTFkNWIyOTg4ZmYzNjRjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pLvJpgUsJRsEWgymPfldMhSBZTJ2s5Rqqp-eaT3okhw">
> I tried the following steps on mac:
> 
> 1. `cd ~/.vscode/extensions`
> 2. `ls` to list the extensions
> 3. `cd <name of rvest.prettier extension directory>`
> 4. `npm i`
> 
> <img alt="image" width="1128" src="https://private-user-images.githubusercontent.com/21978023/380792080-b18b14ce-497d-40c2-98fa-4f6e954b3c74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTExMDQsIm5iZiI6MTczMjcxMDgwNCwicGF0aCI6Ii8yMTk3ODAyMy8zODA3OTIwODAtYjE4YjE0Y2UtNDk3ZC00MGMyLTk4ZmEtNGY2ZTk1NGIzYzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNjEyMGZmNTMzYTNmYzkyNWEzZmVkMDAyMjhkNjk2MmFmNTMxNGU1OTYyMjdjMTEwNThhOTdjOTcxNTgzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iZww9EPPWreAfOB_t5H5vlFFBzTETagZNx-eYwRboh4"> then output for extension showed: <img alt="image" width="1708" src="https://private-user-images.githubusercontent.com/21978023/380792169-4ebd4a03-ffdd-4ce9-a800-12d01d048f26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTExMDQsIm5iZiI6MTczMjcxMDgwNCwicGF0aCI6Ii8yMTk3ODAyMy8zODA3OTIxNjktNGViZDRhMDMtZmZkZC00Y2U5LWE4MDAtMTJkMDFkMDQ4ZjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMTJkN2RmMDdjOGNmZmRiYjcyMjg3MzRmYjY2ODg1ZWY5YTgwOGJlMjdlMzcxMGU5M2M3NzQ2NmFlYTk3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n8GNy5632jUX46yKnaLieum9I60EY8ODhjfdGPBoPKE">

Ok, i check it
