### ISSUE TITLE
Doesn't work with tailwind

### ISSUE THREAD

**Issue by Igor-Vuk** [idahogurl/vs-code-prettier-eslint#234]
By using "prettier-plugin-tailwindcss" and adding `"plugins": ["prettier-plugin-tailwindcss"]` to .prettierrc.json prettier stops working for any type of file. If I remove this line it works for everything except the tailwind classes.

I also tried "eslint-plugin-tailwindcss" without changing ".prettierrc.json" I get lines below the code where there is a tailwind error. This is coming from Eslint, but on save prettier doesn't format tailwind classes. It does the rest of the code.

**Comment by jsonMartin** [comment]
I'm also having this same issue. `prettier-eslint` does not work with `"prettier-plugin-tailwindcss"` in the VSCode plugin

**Comment by tylerlu-hivemapper** [comment]
Running into the same issue

**Comment by bravo-kernel** [comment]
Works great with https://github.com/francoismassart/eslint-plugin-tailwindcss
