### ISSUE TITLE
Feature request: format all docs in a directory

### ISSUE THREAD

**Issue by leegee** [idahogurl/vs-code-prettier-eslint#24]
As a happy user,
I would like to run your lovely formatter recursively over a directory 
formatting each file that matches a user-configurable regexp/glob
When right-clicking the 'File Explorer', 
Then an option is presented in the context menu to 'Format all' against directories
(and perhaps 'format' against files?

**Comment by idahogurl** [comment]
@leegee I can see how that would be useful. Would it really need the regexp/glob? The .eslintignore & .prettierignore would make sure to skip over files you don't want ever formatted.
