### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Ayushi-Sharma** [idahogurl/vs-code-prettier-eslint#28]
- Issue Type: `Bug`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `3.0.4`
- OS Version: `Darwin x64 20.6.0`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by idahogurl** [comment]
@Ayushi-Sharma Could you provide further clarification and reproduction steps for this bug?
