### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by fattah-behmadi** [idahogurl/vs-code-prettier-eslint#29]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Example Project**

 (If possible, please create an example project here on GitHub.com that exhibits the problematic
 behavior, and link to it here in the bug report.
 If you are using an older version of GitHub, this will also determine whether the bug has been fixed
 in a more recent version)

**Screenshots**

**Versions (please complete the following information):**
- Visual Studio Code: [e.g 1.57.1]
- Node: [e.g. 12.21.0]
- Package Manager [e.g. npm 7.18.1, yarn 1.22.10, pnpm 6.7.6]
- prettier-eslint: [e.g. 10.1.0]
- prettier: [e.g. 1.9.2]
- eslint: [e.g. 6.8.0]

**System Specifications (please complete the following information):**
- OS: [e.g. MacOS Big Sur 11.4]
- Processor: [e.g. Intel i7 2.6Ghz]
- RAM Size: [e.g. 16 GB]
 
**Additional context**

**Comment by idahogurl** [comment]
@fattah-behmadi Thank you for creating an issue. Could you please provide steps or example project to reproduce the issue? Otherwise, I'll have to mark this as closed.
