### ISSUE TITLE
Activating extension rvest.vs-code-prettier-eslint failed due to an error

### ISSUE THREAD

**Issue by githuber0007** [idahogurl/vs-code-prettier-eslint#36]
**Describe the bug**
An error occurred loading extension preview 5.0.0

**To Reproduce**
1. Open the extended host log to see this error message

**Screenshots**
![image](https://user-images.githubusercontent.com/56445536/165480825-faf3eb87-a0f9-4496-a7ee-3ae3d22fd79b.png)

**Versions (please complete the following information):**
- Visual Studio Code: 1.66.2
- Node: v16.13.2
- Package Manager: npm@8.7.0
- prettier-eslint@14.0.1
- prettier@2.5.1
- eslint@8.7.0

**System Specifications (please complete the following information):**
- OS: Windows 10 20H2(19042.867)
- Processor: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz   2.80 GHz
- RAM Size: 32.0 GB

**Comment by idahogurl** [comment]
@githuber0007 Could you create an example repository. I cannot seem to reproduce the issue.

**Comment by idahogurl** [comment]
Closed by #37
