### ISSUE TITLE
ESLint stage is not applied

### ISSUE THREAD

**Issue by Hetch3t** [idahogurl/vs-code-prettier-eslint#38]
**Describe the bug**
Seems like `eslint --fix` stage is not applied at all (typescript file).

**To Reproduce**
Steps to reproduce the behaviour:
1. Have `.eslintrc.json` config file. 
2. Set `prettier` config via `package.json`. 
3. Have `.ts` file to format.
4. Test 1:
4.1. Install `prettier` extension (for testing purposes) and ESLint extension:
4.2. `CMD + SHIFT + P` -> `Format document with` -> `Prettier`
4.3. `CMD + SHIFT + P` -> `ESLINT: Fix all auto-fixable`
4.4. Observe expected changes. Remember the state*
4.5. Undo changes
4.6. Run `CMD + SHIFT + P` -> `Format document with` -> `Prettier-ESLint`
4.7. Compare with (*) - see the difference.
5. Test 2:
5.1. Create `prettier-eslint-test.js` file
5.2. Import both configs, import `prettier-eslint`
5.3. `fs.readFileSync(...).toString` `ts` file to format to provide as a source
5.4. Run `format`
5.5. Validate that it looks like it should, NOT how the extension provides it => Issue with extension, not with `prettier-eslint` package.

**Expected behavior**
ESLint stage executed. 

**Example Project**
- [Prettier config used](https://github.com/Hetch3t/eslint-config/blob/v0.0.1/src/prettier.js)
- [ESLint TS config used](https://github.com/Hetch3t/eslint-config/blob/v0.0.1/src/ts.js) (which is highly dependent on [ESLint JS config](https://github.com/Hetch3t/eslint-config/blob/v0.0.1/src/js.js) in the same repo)

**Versions (please complete the following information):**
- Visual Studio Code: 1.67.0
- Node: 18.0.0
- Package Manager: yarn 1.22.18
- prettier-eslint: 14.0.2
- prettier: 2.6.2
- eslint: 8.15.0

**System Specifications (please complete the following information):**
- OS: macOS Monterey 12.3.1
- Processor: 2,6 GHz 6-Core Intel Core i7
- RAM Size: 16 GB
 
**Additional context**
Used the provided above configs in other project via:
`package.json`:
```json
"prettier": "@hetchet/eslint-config/prettier",
"devDependencies": {
		"@hetchet/eslint-config": "https://github.com/Hetch3t/eslint-config-hetchet#9a47109a4957a57fc68058a4c0e56fa81211a066",
		...
}
```
`ESLint`:
```json
{
	"extends": ["@hetchet/eslint-config/ts"],
	"parserOptions": {
		"project": "./tsconfig.json"
	},
	"ignorePatterns": ["packages/**/dist/*"],
}
```

^-- With the config above `Prettier Format` + `ESLint fix-all` work as expected, however, `Prettier-ESLint Format` executes (no errors in Output as well), but looks like it completely ignores ESLint rules (e.g. `'import/newline-after-import': ['error', { count: 2 }]` (2 empty lines after import) or `'space-before-function-paren': 'error'` are completely ignored).

**Comment by Hetch3t** [comment]
Okay, I was able to fix this. Issue is with:
```json
"parserOptions": {
		"project": "./tsconfig.json"
	},
```

So I excluded rules that were requiring setting `parserOptions.project`

**Comment by tabcat** [comment]
Having same issue. The ESLint rules are not being applied.
