### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ipetinate** [idahogurl/vs-code-prettier-eslint#39]
- Issue Type: `Performance`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `3.1.0`
- OS Version: `Darwin x64 21.4.0`
- VS Code version: `1.67.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/yv/x7jphpzx7ybddzwz0_jxsrym0000gq/T/rvest.vs-code-prettier-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by idahogurl** [comment]
@ipetinate Could you provide the following?

**Versions (please complete the following information):**
- Node: [e.g. 12.21.0]
- prettier-eslint: [e.g. 10.1.0]
- prettier: [e.g. 1.9.2]
- eslint: [e.g. 6.8.0]

**System Specifications (please complete the following information):**
- OS: [e.g. MacOS Big Sur 11.4]
- Processor: [e.g. Intel i7 6-Core 2.6Ghz]
- RAM Size: [e.g. 16 GB]

Also, how many line numbers and how big (kB/MB) was the file you were attempting to format?

**Comment by ipetinate** [comment]
- **Versions (please complete the following information):**
    - Node: 14.19.1
    - prettier: 2.2.1
    - eslint: 7.22.0
- **System Specifications (please complete the following information):**
    - OS: macOS Monterey 12.3.1
    - Processor: 2,6 GHz Intel Core i7 6-Core
    - RAM Size: 16 GB 2667 MHz DDR4
    - Graphics: Intel HD + AMD Radeon Pro 5300M 4 GB
- A: Also, how many line numbers and how big (kB/MB) was the file you were attempting to format?
    - R: approximately 500 lines
 
Apparently it was an ESLint problem, because when I gave a CMD + S Prettier formatted the file instantly.

**Comment by idahogurl** [comment]
@ipetinate That's really strange. Your system is basically the same as my old machine before I got an M1 and it didn't have CPU  issues with a file that small. When I had a quad core processor, I did notice some lagginess. Do you have the same issue with running the ESLint CLI?

**Comment by ipetinate** [comment]
No, that doesn't happen when running the cli.
I believe it is some conflict between VS Code extensions.
