### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by zhaojunyan9528** [idahogurl/vs-code-prettier-eslint#4]
- Issue Type: `Bug`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `3.0.4`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.57.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by idahogurl** [comment]
@zhaojunyan9528 What's the error you are receiving? Could you provide a reproduction repository with steps to reproduce?

**Comment by idahogurl** [comment]
Closing issue due to over 14 days of inactivity.
