### ISSUE TITLE
Prettier-eslint plug-in does not respect .prettierrc file

### ISSUE THREAD

**Issue by 123names** [idahogurl/vs-code-prettier-eslint#40]
**Describe the bug**
I have a .prettierrc file contain property 
{ 
  "trailingComma": "all"
}
with settting.json I have 
{ 
  "csharpextensions.privateMemberPrefix": "_",
  "csharpextensions.useThisForCtorAssignments": false,
  "cSpell.userWords": ["connectionless", "Datagram", "nextjs"],
  "editor.bracketPairColorization.enabled": true,
  "editor.defaultFormatter": "rvest.vs-code-prettier-eslint",
  "editor.foldingStrategy": "indentation",
  "editor.formatOnSave": true,
  "editor.linkedEditing": true,
  "git.autofetch": true,
  "git.enableSmartCommit": true,
  "gitlens.hovers.currentLine.over": "line",
  "omnisharp.enableImportCompletion": true,
  "python.terminal.executeInFileDir": true,
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "typescript.updateImportsOnFileMove.enabled": "always",
  "workbench.iconTheme": "material-icon-theme",
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
  },
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
  },
  "[scss]": {
    "editor.defaultFormatter": null
  },
  "[typescript]": {
    "editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
  },
  "[json]": {
    "editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
  },
}

every time I save file, it delete the trailing Comma with cause me to fail the remote code check
![image](https://user-images.githubusercontent.com/13399367/170801487-d4b95edc-cdcd-4c7d-a91f-78df34e24d6a.png). 
I have to manually run command "prettier": "prettier --write ./**/*.ts", to fix the style, then push the changes.

From what I check, it ignored the entire local .prettierrc file, is there a place where we can set it to use local .prettierrc file instead of default prettier settings?
Although I installed the extension prettier and Eslint, but I disabled it for this workspace so it shouldn't have any influence.

**To Reproduce**
just create a file with multiple functions to export 
export {
  fuction1,
  fuction2,
  fuction3,
  fuction4,
  fuction5
};

**Expected behavior**
export {
  fuction1,
  fuction2,
  fuction3,
  fuction4,
  fuction5,
};

**Example Project**
sorry can't really provide any example project, but it's 

**Screenshots**
not applicable

**Versions (please complete the following information):**
- Version: 1.67.2 
- Node.js: v14.19.1
- Package Manager [npm 8.11.0]
- prettier-eslint: [e.g. 14.0.2]
- prettier: [e.g. 2.6.2]
- eslint: [e.g. 7.32.0]

**System Specifications (please complete the following information):**
- OS: Windows_NT x64 10.0.22000
- RAM Size: [16 GB]
 
**Additional context**
Sorry, doesn't 100% sure the bug is from the plugin or the prettier itself since no information is given when I try to debug this plugin.
![image](https://user-images.githubusercontent.com/13399367/170801804-5402360b-0da2-459b-82b3-2a48554426c8.png)

Date: 2022-05-17T18:15:52.058Z

**Comment by idahogurl** [comment]
@123names What version of VS Code Prettier ESLint are you running? I'll have to do some further checking but one thing I noticed is that your ESLint version is on version 7 and only version 4.10 of my plugin works with 7. Version 5 requires 8

**Comment by 123names** [comment]
> I'll have to do some further checking but one thing I noticed is that your ESLint version is on version 7 and only version 4.10 of my plugin works with 7. Version 5 requires 8

![image](https://user-images.githubusercontent.com/13399367/171701087-38a69522-d4de-4f85-995e-c955d60a04e3.png)

**Comment by idahogurl** [comment]
@123names Could I get your ESLint config?

**Comment by idahogurl** [comment]
@123names I created a project to try to reproduce the behavior. https://github.com/idahogurl/vs-code-prettier-eslint-40
I have been unsuccessful in getting the issue to reproduce. I ran `prettier *.ts --write` and even it doesn't put a comma after the last function exported. See https://github.com/idahogurl/vs-code-prettier-eslint-40/blob/main/test.ts

**Comment by 123names** [comment]
I think it's what in .prettierrc cause the comma.
{
  "singleQuote": true,
  "jsxSingleQuote": true,
  "printWidth": 120,
  "tabWidth": 2,
  "useTabs": false,
  "trailingComma": "es5",
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine": "auto"
}

**Comment by the-vampiire** [comment]
@123names does it help if you add this rule?

```js

    "comma-dangle": ["error", "always-multiline"]
```

**Comment by idahogurl** [comment]
@123names From the terminal I ran the command `npx prettier *.ts --write`. I was not in the editor.
