### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hasibul442** [idahogurl/vs-code-prettier-eslint#47]
- Issue Type: `Performance`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `5.0.3`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/hasib/AppData/Local/Temp/rvest.vs-code-prettier-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by idahogurl** [comment]
@[hasibul442](https://github.com/hasibul442) Thank you for creating an issue and providing some help to resolve it. I am aware of performance issues with quad-core or smaller processors. Being on Windows NT makes me think you are on an older machine. I need the cpuprofile.txt to know what is causing this issue.

Do you have autosave set to onFocusChange?

**Comment by hasibul442** [comment]
@idahogurl Thanks for your reply. I am very sorry because i clean my temp folder very recently.
