### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AkanWealth** [idahogurl/vs-code-prettier-eslint#6]
- Issue Type: `Performance`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `3.0.4`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.58.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\AKANWE~1\AppData\Local\Temp\rvest.vs-code-prettier-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by idahogurl** [comment]
@AkanWealth Thank you for creating an issue and providing some help to resolve it. I am aware of performance issues with quad-core or smaller processors. Being on Windows NT makes me think you are on an older machine. I'll see what is causing the high cpu load but I'm afraid my hands are tied if it points to the Prettier-ESLint package.

Do you have auto save set to `onFocusChange`?

**Comment by idahogurl** [comment]
@AkanWealth I need that `cpuprofile.txt` file. It didn't get attached.
