### ISSUE TITLE
Eslint not working

### ISSUE THREAD

**Issue by kaname-png** [idahogurl/vs-code-prettier-eslint#63]
**Describe the bug**
When I install the prettier extension it seems to work fine, but no eslint rule loads. Because for example I have a rule not to put a class and a non-public constructor, but with this extension I don't get any error on eslint.

Prettier works fine "I think" because the document is formatted as I have configured in my prettier rules.

**To Reproduce**
1. Install extension
2. open a file with wrong eslint rules applyed
3. See error

**Expected behavior**

Using official eslint extension of microsoft:

![image](https://user-images.githubusercontent.com/56084970/181861393-6bf78363-558a-4893-9097-99614e8cd1a7.png)

**Example Project**

 (If possible, please create an example project here on GitHub.com that exhibits the problematic
 behavior, and link to it here in the bug report.
 If you are using an older version of GitHub, this will also determine whether the bug has been fixed
 in a more recent version)

**Screenshots**
Using this extension:

![image](https://user-images.githubusercontent.com/56084970/181861442-6b29f9a9-85d2-4983-9d0c-0c3eed7e1170.png)

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension 5.0.4
- Visual Studio Code: 1.70.0
- Node: 18.0.0
- Package Manager yarn berry
- prettier: 2.7.1
- eslint: 8.20.0

**System Specifications (please complete the following information):**
- OS: Windows 11 22000.795
- Processor: AMD Ryzen 3 3200G
- RAM Size: 16 GB
 
**Additional context**
This is the eslint configuration (.eslintrc) file that I have, it extends an npm package, which works fine because with the official microsoft extension it works perfectly.

```json
{
	"extends": "@sapphire"
}
```

`package.json`

```json
{
	"@sapphire/eslint-config": "^4.3.7"
}
```

**Comment by mattbrannon** [comment]
@kaname-png Just to be clear, is your issue with ESLint not displaying information about rule violations in the editor? If so, that's not what this extension does. If you want that you also need to have the ESLint extension installed.

**Comment by idahogurl** [comment]
@kaname-png @mattbrannon  is right this is not a bug. You need the ESLint extension and VS Code Prettier ESLint extension installed. VS Code Prettier ESLint is only a formatter.
