### ISSUE TITLE
probleem  1 

### ISSUE THREAD

**Issue by majidini** [idahogurl/vs-code-prettier-eslint#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Example Project**

 (If possible, please create an example project here on GitHub.com that exhibits the problematic
 behavior, and link to it here in the bug report.
 If you are using an older version of GitHub, this will also determine whether the bug has been fixed
 in a more recent version)

**Screenshots**

**Versions (please complete the following information):**
- Visual Studio Code: [e.g 1.57.1]
- Node: [e.g. 12.21.0]
- Package Manager [e.g. npm 7.18.1, yarn 1.22.10, pnpm 6.7.6]
- prettier-eslint: [e.g. 10.1.0]
- prettier: [e.g. 1.9.2]
- eslint: [e.g. 6.8.0]

**System Specifications (please complete the following information):**
- OS: [e.g. MacOS Big Sur 11.4]
- Processor: [e.g. Intel i7 2.6Ghz]
- RAM Size: [e.g. 16 GB]
 
**Additional context**

> [``](

- #3 

- [ ] @

1. 

- 

> `[](url)`

- [ ] url

)

**Comment by idahogurl** [comment]
@majidini Could I get some clear reproduction steps and/or example repository?
