### ISSUE TITLE
"Format Document With" doesn't work the same as codeActionsOnSave

### ISSUE THREAD

**Issue by alecrobertson1** [idahogurl/vs-code-prettier-eslint#84]
**Describe the bug**

With editor.codeActionsOnSave.source.fixAll set to true, on save ESLint and Prettier run as expected.

But when using Format Document/Format Document With Prettier ESLint, formatting does not work as expected.

Specifically, the extension "simple-import-sort" only works when using source.fixAll, _not_ when using "Format Document".

**To Reproduce**

**Expected behavior**

Both should behave the same.

**Example Project**

 (If possible, please create an example project here on GitHub.com that exhibits the problematic
 behavior, and link to it here in the bug report.
 If you are using an older version of GitHub, this will also determine whether the bug has been fixed
 in a more recent version)

**Screenshots**

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension [e.g. 3.1.0] 5.0.4
- Visual Studio Code: [e.g 1.57.1] 1.71.1
- Node: [e.g. 12.21.0] 14.19.3
- Package Manager [e.g. npm 7.18.1, yarn 1.22.10, pnpm 6.7.6] yarn 1.22.17
- prettier: [e.g. 1.9.2] 2.7.1
- eslint: [e.g. 6.8.0] 8.21.0

**System Specifications (please complete the following information):**
- OS: [e.g. MacOS Big Sur 11.4] macOS 12.5.1
- Processor: [e.g. Intel i7 6-core 2.6Ghz] Apple M1 Pro
- RAM Size: [e.g. 16 GB] 16GB
 
**Additional context**

**Comment by idahogurl** [comment]
@alecrobertson1 Could you create an example project or at least attach your ESLint config file?

**Comment by Quineone** [comment]
Have the same issue
