### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by kishanlalbj** [idahogurl/vs-code-prettier-eslint#9]
- Issue Type: `Bug`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `3.0.4`
- OS Version: `Darwin x64 20.5.0`
- VS Code version: `1.58.2`

:warning: extension is not responding :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 9,
		"activateCallTime": -1,
		"activateResolvedTime": -1,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "rvest.vs-code-prettier-eslint",
				"_lower": "rvest.vs-code-prettier-eslint"
			},
			"activationEvent": "onLanguage:javascript"
		}
	},
	"runtimeErrors": []
}
```

**Comment by idahogurl** [comment]
@kishanlalbj Could I get some clear reproduction steps and/or a repository to reproduce?
