### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Metwesh** [idahogurl/vs-code-prettier-eslint#92]
- Issue Type: `Performance`
- Extension Name: `vs-code-prettier-eslint`
- Extension Version: `5.0.4`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.71.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/MOHAME~1/AppData/Local/Temp/rvest.vs-code-prettier-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by idahogurl** [comment]
@Metwesh I'm assuming since you are on Windows NT that you are using an older computer. There is a known performance issue with quad-core processors that I cannot remedy.  The slowness comes from the prettier-eslint package the extension uses.
